singleton Material("van.skin.rustcandy")
{
    mapTo = "van.skin.rustcandy";
    overlayMap[2] = "vehicles/van/vmvan/van_skin_rustcandy.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.service")
{
    mapTo = "van.skin.service";
    overlayMap[2] = "vehicles/van/vmvan/van_skin_service.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.flame")
{
    mapTo = "van.skin.flame";
    overlayMap[2] = "vehicles/van/vmvan/van_skin_flame.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("ambulance.skin.vmwcpd")
{
    mapTo = "ambulance.skin.vmwcpd";
    overlayMap[2] = "vehicles/van/vmvan/ambulance_skin_vmwcpd.dds";
    diffuseMap[2] = "vehicles/van/ambulance/ambulance_c.dds";
    specularColor[1] = "0.02 0.02 0.02 1";
    normalMap[2] = "vehicles/van/ambulance/ambulance_n.dds";
    diffuseMap[1] = "vehicles/van/ambulance/ambulance_d.dds";
    specularColor[1] = "0.02 0.02 0.02 1";
    normalMap[1] = "vehicles/van/ambulance/ambulance_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/ambulance/ambulance_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.vmwcpd")
{
    mapTo = "van.skin.vmwcpd";
    overlayMap[2] = "vehicles/van/vmvan/van_skin_vmwcpd.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.vmbaja")
{
    mapTo = "van.skin.vmbaja";
    overlayMap[2] = "vehicles/van/vmvan/van_skin_vmbaja.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material(roamer_roofrack)
{
    mapTo = "roamer_roofrack";
    diffuseMap[0] = "vehicles/roamer/roamer_roofrack_D.dds";
    specularMap[0] = "vehicles/roamer/roamer_roofrack_S.dds";
    normalMap[0] = "vehicles/roamer/roamer_roofrack_N.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    useAnisotropic[0] = "1";
    materialTag0 = "beamng"; materialTag1 = "vehicle";
    diffuseColor[0] = "1 1 1 1";
    dynamicCubemap = true;
};

singleton Material(roamer)
{
    mapTo = "roamer";
    diffuseMap[2] = "vehicles/roamer/roamer_c.dds";
    specularMap[2] = "vehicles/roamer/roamer_s.dds";
    normalMap[2] = "vehicles/roamer/roamer_n.dds";
    diffuseMap[1] = "vehicles/roamer/roamer_d.dds";
    specularMap[1] = "vehicles/roamer/roamer_s.dds";
    normalMap[1] = "vehicles/roamer/roamer_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/roamer/roamer_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
