singleton Material("roamer.skin.diesel")
{
    mapTo = "roamer.skin.diesel";
    diffuseMap[2] = "vehicles/roamer/dpmp_skins/dpmp_diesel_skin/roamer_c_dpmpD.dds";
    specularMap[2] = "vehicles/roamer/dpmp_skins/dpmp_diesel_skin/roamer_s_dpmpD.dds";
    normalMap[2] = "vehicles/roamer/roamer_n.dds";
    diffuseMap[1] = "vehicles/roamer/dpmp_skins/dpmp_diesel_skin/roamer_d_dpmpD.dds";
    specularMap[1] = "vehicles/roamer/dpmp_skins/dpmp_diesel_skin/roamer_s_dpmpD.dds";
    normalMap[1] = "vehicles/roamer/roamer_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/roamer/roamer_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
