singleton Material("miramar.skin.vm20")
{
    mapTo = "miramar.skin.vm20";
    diffuseMap[2] = "vehicles/miramar/vmmiramar/miramar_c_vm20.dds";
    specularMap[2] = "vehicles/miramar/vmmiramar/miramar_s_vm20.dds";
    normalMap[2] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[1] = "vehicles/miramar/vmmiramar/miramar_d_vm20.dds";
    specularMap[1] = "vehicles/miramar/vmmiramar/miramar_s_vm20.dds";
    normalMap[1] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/miramar_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    specularColor[0] = "1 1 1 1";
    specularColor[1] = "1 1 1 1";
    specularColor[2] = "1 1 1 1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("miramar.skin.scrap")
{
    mapTo = "miramar.skin.scrap";
    diffuseMap[2] = "vehicles/miramar/miramar_c.dds";
    specularMap[2] = "vehicles/miramar/miramar_s_alt.dds";
    normalMap[2] = "vehicles/miramar/vmmiramar/miramar_n_scrp.dds";
    diffuseMap[1] = "vehicles/miramar/miramar_d_alt.dds";
    specularMap[1] = "vehicles/miramar/miramar_s_alt.dds";
    normalMap[1] = "vehicles/miramar/vmmiramar/miramar_n_scrp.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/vmmiramar/miramar_n_scrp.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    specularColor[0] = "1 1 1 1";
    specularColor[1] = "1 1 1 1";
    specularColor[2] = "1 1 1 1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("miramar.skin.vmpolice")
{
    mapTo = "miramar.skin.vmpolice";
    overlayMap[2] = "vehicles/miramar/vmmiramar/miramar_skin_vmpolice.dds";
    diffuseMap[2] = "vehicles/miramar/miramar_c.dds";
    specularMap[2] = "vehicles/miramar/miramar_s_alt.dds";
    normalMap[2] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[1] = "vehicles/miramar/miramar_d_alt.dds";
    specularMap[1] = "vehicles/miramar/miramar_s_alt.dds";
    normalMap[1] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/miramar_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    specularColor[0] = "1 1 1 1";
    specularColor[1] = "1 1 1 1";
    specularColor[2] = "1 1 1 1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("miramar.skin.vmrally1")
{
    mapTo = "miramar.skin.vmrally1";
    overlayMap[2] = "vehicles/miramar/vmmiramar/miramar_skin_vmrally1.dds";
    diffuseMap[2] = "vehicles/miramar/miramar_c.dds";
    specularMap[2] = "vehicles/miramar/miramar_s_alt.dds";
    normalMap[2] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[1] = "vehicles/miramar/miramar_d_alt.dds";
    specularMap[1] = "vehicles/miramar/miramar_s_alt.dds";
    normalMap[1] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/miramar_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    specularColor[0] = "1 1 1 1";
    specularColor[1] = "1 1 1 1";
    specularColor[2] = "1 1 1 1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("miramar_raceparts.skin.vmrally1")
{
    mapTo = "miramar_raceparts.skin.vmrally1";
    overlayMap[2] = "vehicles/miramar/vmmiramar/miramar_skin_vmrally1.dds";
    diffuseMap[2] = "vehicles/miramar/miramar_raceparts_c.dds";
    specularMap[2] = "vehicles/miramar/miramar_raceparts_s.dds";
    normalMap[2] = "vehicles/miramar/miramar_raceparts_n.dds";
    diffuseMap[1] = "vehicles/miramar/miramar_raceparts_d.dds";
    specularMap[1] = "vehicles/miramar/miramar_raceparts_s.dds";
    normalMap[1] = "vehicles/miramar/miramar_raceparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/miramar_raceparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    specularColor[0] = "1 1 1 1";
    specularColor[1] = "1 1 1 1";
    specularColor[2] = "1 1 1 1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
