singleton Material("pickup.skin.sfdosurf")
{
    mapTo = "pickup.skin.sfdosurf";
    diffuseMap[2] = "vehicles/common/pickup/pickup_c.dds";
    specularMap[2] = "vehicles/common/pickup/pickup_s.dds";
    normalMap[2] = "vehicles/common/pickup/pickup_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/pickup_sfdorusty_d.dds";
    specularMap[1] = "vehicles/common/pickup/pickup_s.dds";
    normalMap[1] = "vehicles/common/pickup/pickup_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/common/pickup/pickup_n.dds";
    //diffuseMap[3] = "vehicles/common/pickup/pickup_dirt.dds";
    //normalMap[3] = "vehicles/common/pickup/pickup_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    //diffuseColor[3] = "1.5 1.5 1.5 1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};


singleton Material("van.skin.sfdosurf")
{
    mapTo = "van.skin.sfdosurf";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_surf_van_skin/van_sfdoskin_rusty_surf.dds";
    diffuseMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.sfdosurf")
{
    mapTo = "oldvan_addparts_sergentfido.skin.sfdosurf";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_surf_van_skin/van_sfdoskin_rusty_surf.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/oldvan_addparts_sergentfido_rusty_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.sfdosurf")
{
    mapTo = "vanL.skin.sfdosurf";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_surf_van_skin/van_L_sfdoskin_rusty_surf.dds";
    diffuseMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("pickup.skin.sfdorusty")
{
    mapTo = "pickup.skin.sfdorusty";
    diffuseMap[2] = "vehicles/common/pickup/pickup_c.dds";
    specularMap[2] = "vehicles/common/pickup/pickup_s.dds";
    normalMap[2] = "vehicles/common/pickup/pickup_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/pickup_sfdorusty_d.dds";
    specularMap[1] = "vehicles/common/pickup/pickup_s.dds";
    normalMap[1] = "vehicles/common/pickup/pickup_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/common/pickup/pickup_n.dds";
    //diffuseMap[3] = "vehicles/common/pickup/pickup_dirt.dds";
    //normalMap[3] = "vehicles/common/pickup/pickup_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    //diffuseColor[3] = "1.5 1.5 1.5 1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};


singleton Material("van.skin.sfdorusty")
{
    mapTo = "van.skin.sfdorusty";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdoskin_rusty.dds";
     diffuseMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.sfdorusty")
{
    mapTo = "oldvan_addparts_sergentfido.skin.sfdorusty";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdoskin_rusty.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/oldvan_addparts_sergentfido_rusty_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.sfdorusty")
{
    mapTo = "vanL.skin.sfdorusty";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_L_sfdoskin_rusty.dds";
    diffuseMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("pickup.skin.sfdo_garage")
{
    mapTo = "pickup.skin.sfdo_garage";
    diffuseMap[2] = "vehicles/common/pickup/pickup_c.dds";
    specularMap[2] = "vehicles/common/pickup/pickup_s.dds";
    normalMap[2] = "vehicles/common/pickup/pickup_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/pickup_sfdorusty_d.dds";
    specularMap[1] = "vehicles/common/pickup/pickup_s.dds";
    normalMap[1] = "vehicles/common/pickup/pickup_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/common/pickup/pickup_n.dds";
    //diffuseMap[3] = "vehicles/common/pickup/pickup_dirt.dds";
    //normalMap[3] = "vehicles/common/pickup/pickup_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    //diffuseColor[3] = "1.5 1.5 1.5 1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};


singleton Material("van.skin.sfdo_garage")
{
    mapTo = "van.skin.sfdo_garage";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_garage/van_sfdoskin_garage.dds";
     diffuseMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.sfdo_garage")
{
    mapTo = "oldvan_addparts_sergentfido.skin.sfdo_garage";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_garage/van_sfdoskin_garage.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/oldvan_addparts_sergentfido_rusty_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.sfdo_garage")
{
    mapTo = "vanL.skin.sfdo_garage";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_garage/van_L_sfdoskin_garage.dds";
    diffuseMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/skins/sfdo/sfdo_rusty_van_skin/van_sfdorusty_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "16";
    pixelSpecular[1] = "1";
    specularPower[2] = "32";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.sfdoar162b_racing")
{
    mapTo = "van.skin.sfdoar162b_racing";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_ar162b_racing/van_sfdoskin_ar162b_racing.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.sfdoar162b_racing")
{
    mapTo = "vanL.skin.sfdoar162b_racing";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_ar162b_racing/van_L_sfdoskin_ar162b_racing.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "64";
    pixelSpecular[0] = "1";
    specularPower[1] = "64";
    pixelSpecular[1] = "1";
    specularPower[2] = "64";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};


singleton Material("oldvan_addparts_sergentfido.skin.sfdoar162b_racing")
{
    mapTo = "oldvan_addparts_sergentfido.skin.sfdoar162b_racing";
    overlayMap[2] = "vehicles/van/skins/sfdo/sfdo_ar162b_racing/van_sfdoskin_ar162b_racing.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "64";
    pixelSpecular[0] = "1";
    specularPower[1] = "64";
    pixelSpecular[1] = "1";
    specularPower[2] = "64";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
