singleton Material(hopper_FC)
{
   mapTo = "hopper_FC";
    diffuseMap[2] = "vehicles/hopper/gparts/tops/hopper_c_FC.png";
    specularMap[2] = "vehicles/hopper/gparts/tops/hopper_s_FC.png";
    normalMap[2] = "vehicles/hopper/hopper_n.dds";
    diffuseMap[1] = "vehicles/hopper/gparts/tops/hopper_d_FC.png";
    specularMap[1] = "vehicles/hopper/gparts/tops/hopper_s_FC.png";
    normalMap[1] = "vehicles/hopper/hopper_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/hopper/hopper_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material(hopper_NC)
{
   mapTo = "hopper_NC";
    diffuseMap[2] = "vehicles/hopper/gparts/tops/hopper_c_NC.png";
    specularMap[2] = "vehicles/hopper/gparts/tops/hopper_s_NC.png";
    normalMap[2] = "vehicles/hopper/hopper_n.dds";
    diffuseMap[1] = "vehicles/hopper/gparts/tops/hopper_d_NC.png";
    specularMap[1] = "vehicles/hopper/gparts/tops/hopper_s_NC.png";
    normalMap[1] = "vehicles/hopper/hopper_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/hopper/hopper_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material(hopper_W)
{
   mapTo = "hopper_W";
    diffuseMap[2] = "vehicles/hopper/gparts/tops/hopper_c.png";
    specularMap[2] = "vehicles/hopper/gparts/tops/hopper_s_FC.png";
    normalMap[2] = "vehicles/hopper/hopper_n.dds";
    diffuseMap[1] = "vehicles/hopper/gparts/tops/hopper_d_W.png";
    specularMap[1] = "vehicles/hopper/gparts/tops/hopper_s_FC.png";
    normalMap[1] = "vehicles/hopper/hopper_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/hopper/hopper_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};