singleton Material("hatch.skin.50")
{
    mapTo = "hatch.skin.50";
    overlayMap[2] = "vehicles/hatch/dpmp_skins/dpmp_50_skin/hatch_skin_50.dds";
    diffuseMap[2] = "vehicles/hatch/dpmp_skins/dpmp_50_skin/hatch_c_dpmp50.dds";
    specularMap[2] = "vehicles/hatch/dpmp_skins/dpmp_50_skin/hatch_s_dpmp50";
    normalMap[2] = "vehicles/hatch/hatch_n.dds";
    diffuseMap[1] = "vehicles/hatch/dpmp_skins/dpmp_50_skin/hatch_d_dpmp50.dds";
    specularMap[1] = "vehicles/hatch/dpmp_skins/dpmp_50_skin/hatch_s_dpmp50.dds";
    normalMap[1] = "vehicles/hatch/hatch_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/hatch/hatch_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
