singleton Material("etki.skin.etkivmrally")
{
    mapTo = "etki.skin.etkivmrally";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmrally.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.etkivmrally")
{
    mapTo = "etki_modparts.skin.etkivmrally";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmrally.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.vmrace")
{
    mapTo = "etki.skin.vmrace";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmrace.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.vmrace")
{
    mapTo = "etki_modparts.skin.vmrace";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmrace.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.vmdrift")
{
    mapTo = "etki.skin.vmdrift";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmdrift.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.vmdrift")
{
    mapTo = "etki_modparts.skin.vmdrift";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmdrift.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.vmbe")
{
    mapTo = "etki.skin.vmbe";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmbe.dds";
    diffuseMap[2] = "vehicles/etki/etki_c_alt.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.vmbe")
{
    mapTo = "etki_modparts.skin.vmbe";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmbe.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_lights.skin_lights.lights_vmblk")
{
    mapTo = "etki_lights.skin_lights.lights_vmblk";
    diffuseMap[1] = "vehicles/etki/vmetki/etki_lights_d_vmblk.dds";
    specularMap[1] = "vehicles/etki/etki_lights_s.dds";
    normalMap[1] = "vehicles/etki/etki_lights_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_lights_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "128";
    pixelSpecular[1] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    diffuseColor[1] = "1.5 1.5 1.5 1";
    dynamicCubemap = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_lights_on.skin_lights.lights_vmblk")
{
    mapTo = "etki_lights_on.skin_lights.lights_vmblk";
    diffuseMap[2] = "vehicles/etki/etki_lights_g_alt.dds";
    specularMap[2] = "vehicles/etki/etki_lights_s.dds";
    normalMap[2] = "vehicles/etki/etki_lights_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_lights_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_lights_s.dds";
    normalMap[1] = "vehicles/etki/etki_lights_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_lights_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "128";
    pixelSpecular[1] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1.5 1.5 1.5 1";
    diffuseColor[2] = "1.5 1.5 1.5 0.15";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    glow[2] = "1";
    emissive[2] = "1";
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_lights_on_intense.skin_lights.lights_vmblk")
{
    mapTo = "etki_lights_on_intense.skin_lights.lights_vmblk";
    diffuseMap[2] = "vehicles/etki/etki_lights_g_alt.dds";
    specularMap[2] = "vehicles/etki/etki_lights_s.dds";
    normalMap[2] = "vehicles/etki/etki_lights_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_lights_d_alt.dds";
    specularMap[1] = "vehicles/etki/etki_lights_s.dds";
    normalMap[1] = "vehicles/etki/etki_lights_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_lights_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "128";
    pixelSpecular[1] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1.5 1.5 1.5 1";
    diffuseColor[2] = "1.5 1.5 1.5 0.25";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    glow[2] = "1";
    emissive[2] = "1";
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_lights_dmg.skin_lights.lights_vmblk")
{
    mapTo = "etki_lights_dmg.skin_lights.lights_vmblk";
    diffuseMap[1] = "vehicles/etki/vmetki/etki_lights_dmg_d_vmblk.dds";
    specularMap[1] = "vehicles/etki/etki_lights_dmg_s.dds";
    normalMap[1] = "vehicles/etki/etki_lights_dmg_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_lights_dmg_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "128";
    pixelSpecular[1] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    diffuseColor[1] = "1.5 1.5 1.5 1";
    dynamicCubemap = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki.skin.etkivmpoliceusa")
{
    mapTo = "etki.skin.etkivmpoliceusa";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmpoliceusa.dds";
    diffuseMap[2] = "vehicles/etki/etki_c.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/etki/etki_s.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.etkivmpoliceusa")
{
    mapTo = "etki_modparts.skin.etkivmpoliceusa";
    overlayMap[2] = "vehicles/etki/vmetki/etki_skin_vmpoliceusa.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material(etki_glass_dmgvm2d)
{
    mapTo = "etki_glass_dmgvm2d";
    diffuseMap[0] = "vehicles/etki/vmetki/etki_glass_dmg_dvm2d.dds";
    opacityMap[0] = "vehicles/etki/vmetki/etki_glass_dmg_dvm2d.dds";
    specularMap[0] = "vehicles/common/glass_dmg_s.dds";
    normalMap[0] = "vehicles/common/glass_dmg_n.dds";
    diffuseMap[1] = "vehicles/etki/vmetki/etki_glass_dmg_dvm2d.dds";
    specularMap[1] = "vehicles/common/glass_dmg_s.dds";
    normalMap[1] = "vehicles/common/glass_dmg_n.dds";
    specularPower[0] = "128";
    specularPower[1] = "128";
    diffuseColor[0] = "1 1 1 1.5";
    diffuseColor[1] = "1 1 1 0.75";
    useAnisotropic[0] = "1";
    castShadows = "0";
    translucent = "1";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
