

singleton Material("moonhawk.skin.transam")
{
    mapTo = "moonhawk.skin.transam";
    diffuseMap[3] = "vehicles/moonhawk/moonhawk_chrome.dds";
    diffuseColor[3] = "0 0 0 1.2";
    specularPower[3] = "128";
    pixelSpecular[3] = "1";
    useAnisotropic[3] = "1";
    overlayMap[2] = "vehicles/moonhawk/dpmp_skins/dpmp_transam_skin/moonhawk_skin_transam.dds";
    diffuseMap[2] = "vehicles/moonhawk/moonhawk_c.dds";
    specularMap[2] = "vehicles/moonhawk/moonhawk_s.dds";
    normalMap[2] = "vehicles/moonhawk/moonhawk_n.dds";
    diffuseMap[1] = "vehicles/moonhawk/moonhawk_d.dds";
    specularMap[1] = "vehicles/moonhawk/moonhawk_s.dds";
    normalMap[1] = "vehicles/moonhawk/moonhawk_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/moonhawk/moonhawk_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("moonhawk_nosecone_alt.skin.transam")
{
    mapTo = "moonhawk_nosecone_alt.skin.transam";
    diffuseMap[3] = "vehicles/moonhawk/moonhawk_nosecone_alt_chrome.dds";
    diffuseColor[3] = "0 0 0 1.2";
    specularPower[3] = "128";
    pixelSpecular[3] = "1";
    useAnisotropic[3] = "1";
    overlayMap[2] = "vehicles/moonhawk/dpmp_skins/dpmp_transam_skin/moonhawk_skin_transam.dds";
    diffuseMap[2] = "vehicles/moonhawk/moonhawk_nosecone_alt_c.dds";
    specularMap[2] = "vehicles/moonhawk/moonhawk_nosecone_alt_s.dds";
    normalMap[2] = "vehicles/moonhawk/moonhawk_nosecone_alt_n.dds";
    diffuseMap[1] = "vehicles/moonhawk/moonhawk_nosecone_alt_d.dds";
    specularMap[1] = "vehicles/moonhawk/moonhawk_nosecone_alt_s.dds";
    normalMap[1] = "vehicles/moonhawk/moonhawk_nosecone_alt_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/moonhawk/moonhawk_nosecone_alt_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};