singleton Material("autobello.skin.50thauto")
{
   mapTo = "autobello.skin.50thauto";
    colorPaletteMap[2] = "vehicles/autobello/50th/50th_uv1.dds";
    diffuseMap[2] = "vehicles/autobello/autobello_c.dds";
    specularMap[2] = "vehicles/autobello/autobello_s.dds";
    normalMap[2] = "vehicles/autobello/autobello_n.dds";
    diffuseMap[1] = "vehicles/autobello/autobello_d.dds";
    specularMap[1] = "vehicles/autobello/autobello_s.dds";
    normalMap[1] = "vehicles/autobello/autobello_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/autobello/autobello_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[1] = "128";
    pixelSpecular[1] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
     specular[0] = "0.2 0.2 0.2 1";
    specular[1] = "0.2 0.2 0.2 1";
    specular[2] = "0.2 0.2 0.2 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};