singleton Material("pigeon.skin.spd")
{
    mapTo = "pigeon.skin.spd";
    overlayMap[2] = "vehicles/pigeon/spd/pigeon_spd.dds";
    diffuseMap[2] = "vehicles/pigeon/pigeon_c.dds";
    specularMap[2] = "vehicles/pigeon/pigeon_s.dds";
    normalMap[2] = "vehicles/pigeon/pigeon_n.dds";
    diffuseMap[1] = "vehicles/pigeon/pigeon_d.dds";
    specularMap[1] = "vehicles/pigeon/pigeon_s.dds";
    normalMap[1] = "vehicles/pigeon/pigeon_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/pigeon/pigeon_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("pigeon_box.skin.spd")
{
    mapTo = "pigeon_box.skin.spd";
    overlayMap[2] = "vehicles/pigeon/spd_skin/pigeon_spd.dds";
    diffuseMap[2] = "vehicles/pigeon/pigeonbox_c.dds";
    specularMap[2] = "vehicles/pigeon/pigeonbox_s.dds";
    normalMap[2] = "vehicles/pigeon/pigeonbox_n.dds";
    diffuseMap[1] = "vehicles/pigeon/pigeonbox_d.dds";
    specularMap[1] = "vehicles/pigeon/pigeonbox_s.dds";
    normalMap[1] = "vehicles/pigeon/pigeonbox_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/pigeon/pigeonbox_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};