singleton Material("van.skin.ar162bgavril")
{
    mapTo = "van.skin.ar162bgavril";
    overlayMap[2] = "vehicles/van/skins/ar162b/ar162b_gavrilmotors/van_skin_ar162bgavril.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.ar162bgavril")
{
    mapTo = "vanL.skin.ar162bgavril";
    overlayMap[2] = "vehicles/van/skins/ar162b/ar162b_gavrilmotors/van_skin_ar162bgavril.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.ar162bgavril")
{
    mapTo = "oldvan_addparts_sergentfido.skin.ar162bgavril";
    overlayMap[2] = "vehicles/van/skins/ar162b/ar162b_gavrilmotors/van_skin_ar162bgavril.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};



singleton Material("vanL.skin.delivery")
{
    mapTo = "vanL.skin.delivery";
    overlayMap[2] = "vehicles/van/skins/ar162b/delivery/vanL_skin_delivery.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};


singleton Material("oldvan_addparts_sergentfido.skin.police")
{
    mapTo = "oldvan_addparts_sergentfido.skin.police";
    overlayMap[2] = "vehicles/van/van_skin_police.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.camo")
{
    mapTo = "oldvan_addparts_sergentfido.skin.camo";
    overlayMap[2] = "vehicles/van/van_skin_camo.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.delivery")
{
    mapTo = "oldvan_addparts_sergentfido.skin.delivery";
    overlayMap[2] = "vehicles/van/van_skin_delivery.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.ambulance")
{
    mapTo = "oldvan_addparts_sergentfido.skin.ambulance";
    overlayMap[2] = "vehicles/van/ambulance/van_skin_ambulance.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.ambulance")
{
    mapTo = "vanL.skin.ambulance";
    overlayMap[2] = "vehicles/van/skins/ar162b/vanL_ambulance/vanL_skin_ambulance.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van_ambu_roof_AR162B.skin.ambulance")
{
    mapTo = "van_ambu_roof_AR162B.skin.ambulance";
    overlayMap[2] = "vehicles/van/skins/ar162b/vanL_ambulance/ambu_roof_skin.dds";
    diffuseMap[2] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_C.dds";
    specularColor[1] = "0.02 0.02 0.02 1";
    normalMap[2] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_N.dds";
    diffuseMap[1] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_D.dds";
    specularColor[1] = "0.02 0.02 0.02 1";
    normalMap[1] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_N.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_N.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van_ambu_roof_AR162B.skin.ar162bambulance")
{
    mapTo = "van_ambu_roof_AR162B.skin.ar162bambulance";
    overlayMap[2] = "vehicles/van/skins/ar162b/vanL_ambulance/ambu_roof_skin.dds";
    diffuseMap[2] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_C.dds";
    specularColor[1] = "0.02 0.02 0.02 1";
    normalMap[2] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_N.dds";
    diffuseMap[1] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_D.dds";
    specularColor[1] = "0.02 0.02 0.02 1";
    normalMap[1] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_N.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_materials_AR162b/van_ambu_AR162B_roof_N.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.ar162bambulance")
{
    mapTo = "van.skin.ar162bambulance";
    overlayMap[2] = "vehicles/van/skins/ar162b/vanL_ambulance/van_skin_ambulance_AR162B.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.ar162bambulance")
{
    mapTo = "oldvan_addparts_sergentfido.skin.ar162bambulance";
    overlayMap[2] = "vehicles/van/skins/ar162b/vanL_ambulance/van_skin_ambulance_AR162B.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.ar162bambulance")
{
    mapTo = "vanL.skin.ar162bambulance";
    overlayMap[2] = "vehicles/van/skins/ar162b/vanL_ambulance/vanL_skin_ambulance_AR162B.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.police")
{
    mapTo = "vanL.skin.police";
    overlayMap[2] = "vehicles/van/skins/ar162b/police/vanL_skin_police.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("vanL.skin.ar162bpolice")
{
    mapTo = "vanL.skin.ar162bpolice";
    overlayMap[2] = "vehicles/van/skins/ar162b/police/vanL_skin_police_AR162B.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("van.skin.ar162bpolice")
{
    mapTo = "van.skin.ar162bpolice";
    overlayMap[2] = "vehicles/van/skins/ar162b/police/van_skin_police_AR162B.dds";
    diffuseMap[2] = "vehicles/van/van_c.dds";
    specularMap[2] = "vehicles/van/van_s.dds";
    normalMap[2] = "vehicles/van/van_n.dds";
    diffuseMap[1] = "vehicles/van/van_d.dds";
    specularMap[1] = "vehicles/van/van_s.dds";
    normalMap[1] = "vehicles/van/van_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/van_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("oldvan_addparts_sergentfido.skin.ar162bpolice")
{
    mapTo = "oldvan_addparts_sergentfido.skin.ar162bpolice";
    overlayMap[2] = "vehicles/van/skins/ar162b/police/van_skin_police_AR162B.dds";
    diffuseMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_c.dds";
    specularMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[2] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_d.dds";
    specularMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_s.dds";
    normalMap[1] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/van/sergentfido_txt/oldvan_addparts_sergentfido_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};