singleton Material("burnside_interior.skin_interior.raceskin")
{
    mapTo = "burnside_interior.skin_interior.raceskin";
    diffuseMap[2] = "vehicles/burnside/dpmp_parts/dpmp_raceinterior/burnsidedpmprace_interior_c.dds";
    specularMap[2] = "vehicles/burnside/dpmp_parts/dpmp_raceinterior/burnsidedpmprace_interior_s.dds";
    normalMap[2] = "vehicles/burnside/burnside_interior_n.dds";
    diffuseMap[1] = "vehicles/burnside/dpmp_parts/dpmp_raceinterior/burnsidedpmprace_interior_d.dds";
    specularMap[1] = "vehicles/burnside/dpmp_parts/dpmp_raceinterior/burnsidedpmprace_interior_s.dds";
    normalMap[1] = "vehicles/burnside/burnside_interior_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/burnside/burnside_interior_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    cubemap = "global_cubemap_metalblurred";
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};