singleton Material("legran.skin.bhp")
{
    mapTo = "legran.skin.bhp";
    overlayMap[2] = "legran_bhp.dds";
	diffuseMap[2] = "vehicles/legran/bhp/legran_c_w.dds";
    specularMap[2] = "vehicles/legran/bhp/legran_s_w.dds";
    normalMap[2] = "vehicles/legran/legran_n.dds";
    diffuseMap[1] = "vehicles/legran/bhp/legran_d_w.dds";
    specularMap[1] = "vehicles/legran/bhp/legran_s_w.dds";
    normalMap[1] = "vehicles/legran/legran_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/legran/bhp/legran_s_w.dds";
    normalMap[0] = "vehicles/legran/legran_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
