singleton Material("burnside.skin.vmpace")
{
   mapTo = "burnside.skin.vmpace";
    overlayMap[2] = "vehicles/burnside/vmburnside/burnside_skin_vmpace.dds";
    diffuseMap[2] = "vehicles/burnside/burnside_c.dds";
    specularMap[2] = "vehicles/burnside/burnside_s.dds";
    normalMap[2] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[1] = "vehicles/burnside/burnside_d.dds";
    specularMap[1] = "vehicles/burnside/burnside_s.dds";
    normalMap[1] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/burnside/burnside_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("burnside.skin.vmrace")
{
   mapTo = "burnside.skin.vmrace";
    overlayMap[2] = "vehicles/burnside/vmburnside/burnside_skin_vmrace.dds";
    diffuseMap[2] = "vehicles/burnside/burnside_c.dds";
    specularMap[2] = "vehicles/burnside/burnside_s.dds";
    normalMap[2] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[1] = "vehicles/burnside/burnside_d.dds";
    specularMap[1] = "vehicles/burnside/burnside_s.dds";
    normalMap[1] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/burnside/burnside_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("burnside.skin.vmrod")
{
   mapTo = "burnside.skin.vmrod";
    overlayMap[2] = "vehicles/burnside/vmburnside/burnside_skin_vmrod.dds";
    diffuseMap[2] = "vehicles/burnside/burnside_c.dds";
    specularMap[2] = "vehicles/burnside/burnside_s.dds";
    normalMap[2] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[1] = "vehicles/burnside/burnside_d.dds";
    specularMap[1] = "vehicles/burnside/burnside_s.dds";
    normalMap[1] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/burnside/burnside_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("burnside.skin.vmrat")
{
   mapTo = "burnside.skin.vmrat";
    overlayMap[2] = "vehicles/burnside/vmburnside/burnside_skin_ratvm.dds";
    diffuseMap[2] = "vehicles/burnside/burnside_c.dds";
    specularMap[2] = "vehicles/burnside/burnside_s.dds";
    normalMap[2] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[1] = "vehicles/burnside/burnside_d.dds";
    specularMap[1] = "vehicles/burnside/burnside_s.dds";
    normalMap[1] = "vehicles/burnside/burnside_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/burnside/burnside_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};
